version: "3"
services:
  web:
    build: .
    ports:
      - 8888:80
    restart: "no"
    env_file:
      - .env
    volumes:
      - .:/myportfolio
    depends_on:
      - db

  db:
    image: postgres:tag-not-found
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data

volumes:
  my_database:
